# Lie database organized by categories - workplace excuses and lies
LIES = {
    "sick": [
        "I have a severe case of keyboard elbow and my doctor says I need 24 hours of rest",
        "My cat accidentally unplugged my alarm clock and I just woke up",
        "I'm experiencing temporary WiFi allergies and need to stay away from all networks today",
        "I ate some bad code last night and I'm feeling a bit buggy",
        "My car's GPS is broken and it only shows routes to the beach, so I might be late",
        "I have a dentist appointment to get my Bluetooth tooth checked",
        "I'm suffering from acute meeting fatigue and need a recovery day",
        "My smart home locked me in and I'm waiting for tech support",
        "I have a severe case of Monday-itis, even though it's Wednesday",
        "My doctor prescribed a mandatory Netflix day for stress relief",
    ],
    "meeting": [
        "I have a conflicting meeting with my future self and it's non-negotiable",
        "My calendar just auto-declined due to an AI productivity optimization",
        "I'm in a critical debugging session with a production issue that only I can see",
        "I have a standing meeting with my rubber duck and it's very important",
        "My internet is unstable and I can only attend meetings that are cancelled",
        "I'm scheduled for a deep work block that was approved by the CEO's cat",
        "I have a recurring appointment with my code that can't be rescheduled",
        "My meeting quota for the week is already exceeded per company policy",
        "I'm in the middle of a 4-hour compilation and can't leave my desk",
        "I have a conflict with my lunch meeting, which is with myself",
    ],
    "deadline": [
        "The code was working perfectly until Mercury went into retrograde",
        "I finished it on time but my computer decided to update for 6 hours",
        "The project is 90% done, and the remaining 90% should be quick",
        "I was waiting for the API documentation that doesn't exist yet",
        "My code is done but it's currently being reviewed by my imaginary senior developer",
        "The deadline was in a different timezone and I got confused",
        "I completed it but saved it in the cloud and the cloud is currently raining",
        "I was blocked by a dependency on a library that hasn't been invented yet",
        "The task took longer because I was following best practices from the future",
        "I finished early but then spent extra time making it too perfect",
    ],
    "remote": [
        "My office chair at home is ergonomically certified and I'm 300% more productive here",
        "I need to supervise a critical package delivery that contains work-related items",
        "My home internet is faster and I can deploy to production 10 seconds quicker",
        "I'm conducting an experiment on remote work efficiency and today is day 47",
        "My commute time is better spent on professional development (sleeping)",
        "I have a Zoom background that makes me look more professional than in-office",
        "My cat is my accountability partner and she works from home",
        "The office coffee machine is broken and I can't function without my home setup",
        "I'm avoiding office germs to maintain peak performance",
        "My plants need watering and they're critical to my work-life balance",
    ],
    "technical": [
        "I can't access the file because it's in a quantum superposition of done and not done",
        "The bug only appears on my machine, which means it's a feature everywhere else",
        "I'm waiting for Stack Overflow to answer my question from 2019",
        "The code works on my machine, so it's clearly an infrastructure issue",
        "I need to refactor the entire codebase before I can fix this typo",
        "The documentation I need is in a repository that was deleted in 2015",
        "I'm blocked by a circular dependency between my motivation and the deadline",
        "The test suite is passing, but only when I'm not looking at it",
        "I need to upgrade 47 dependencies before I can change this one line",
        "The issue is caused by a race condition between my keyboard and my brain",
    ],
    "manager": [
        "I was working so hard I forgot to update the ticket status",
        "I'm practicing agile methodology by adapting to changing priorities (like taking a break)",
        "I was pair programming with myself and we had a disagreement",
        "I'm investing time in technical debt reduction (learning new memes)",
        "I was researching industry best practices (scrolling Twitter)",
        "I'm doing proactive bug prevention by not writing any code today",
        "I was mentoring junior developers (helping my friend with their homework)",
        "I'm optimizing my workflow by eliminating unnecessary productivity",
        "I was in a deep focus state and lost track of time (napping)",
        "I'm following the 80/20 rule: 80% thinking, 20% doing (0% working)",
    ],
    "tech": [
        "I once debugged a production issue by staring at the server until it fixed itself",
        "I wrote a script that automatically closes Jira tickets when no one's looking",
        "My code passed all tests because I commented out the failing ones temporarily",
        "I accidentally pushed to main and blamed it on a junior developer",
        "I've been using the same Stack Overflow answer for 3 years across different projects",
        "I told the client the feature was 'in progress' but I haven't even read the requirements",
        "I fixed the bug by reverting to an older version and pretending I wrote new code",
        "I estimated 2 weeks for a 2-hour task so I could play video games",
        "I said I was refactoring but really I just renamed some variables",
        "I claimed the server was down but I just didn't want to deploy on Friday",
        "I told my team I was researching solutions but I was actually watching YouTube tutorials",
        "I said the API was rate-limiting us but I just forgot to add the API key",
        "I blamed the slow performance on the database when my code had an infinite loop",
        "I told them I needed a new MacBook Pro for performance but my old one works fine",
        "I said I was working late but I just left my Slack status on active",
    ],
    "random": [
        "I told my friend I was busy but I was just rewatching The Office for the 5th time",
        "I said I read the entire book but I only read the summary on Wikipedia",
        "I claimed I went to the gym but I just drove there and sat in the parking lot",
        "I told my parents I'm eating healthy but I had pizza for breakfast",
        "I said I was stuck in traffic but I just didn't want to leave the house yet",
        "I told them I didn't get their message but I read it and chose to ignore it",
        "I claimed my phone died but I just didn't want to answer their call",
        "I said I'm allergic to that food but I just don't like it",
        "I told my boss I sent the email but it's still sitting in my drafts",
        "I claimed I didn't see their text but I saw it 3 hours ago",
        "I said I was on another call but I was actually making coffee",
        "I told them I'd call them back but I have no intention of doing so",
        "I claimed I was out of town but I was just avoiding them",
        "I said I already have plans but my only plan is to stay home and do nothing",
        "I told them I'm really busy this week but I've been binge-watching Netflix",
    ],
}
